### ISSUE TITLE
Please update dependencies

### ISSUE THREAD

**Issue by crystalfp** [neet/i18next-cli-language-detector#255]
I have installed the latest i18next (v 22.5.0) and the installation of this module complains:
```
D:> npm i i18next-cli-language-detector
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: bib2web@0.2.1
npm ERR! Found: i18next@22.5.0
npm ERR! node_modules/i18next
npm ERR!   i18next@"^22.5.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer i18next@"^21.0.0" from i18next-cli-language-detector@1.1.7
npm ERR! node_modules/i18next-cli-language-detector
npm ERR!   i18next-cli-language-detector@"*" from the root project
. . .
```
I's a minor problem (I hope) but annoying. Could it be fixed?
Thanks!
mario

**Comment by neet** [comment]
Hi Mario, thank you for reporting the issue.

This is because our version requirement was [too strict](https://github.com/neet/i18next-cli-language-detector/blob/38e6f55e76fd16a80e2f2d767e5bb3c7830e4359/package.json#L72) that doesn't accept any other version that doesn't meet the range.

Now I made it tolerant so that it accepts every version without specification. The patch will be released very soon.
